<script lang="ts">
  // Trang Giới thiệu / Giấy phép (UC-U37): ghi công, cơ sở của từng loại thông tin, nguồn dữ liệu, giấy phép.
  // Văn bản dài nên để ở đây (song ngữ) thay vì i18n.svelte.ts. Đường dẫn chỉ hiện dạng chữ (app không mở mạng).
  import { APP_NAME, ui } from "./i18n.svelte";
  import type { DbStatus, Source } from "./types";
  import Badge from "./Badge.svelte";
  import { inTauri } from "./api";
  import { openUrl } from "@tauri-apps/plugin-opener";

  let { sources, status, logo }: { sources: Source[]; status: DbStatus; logo: string } = $props();

  const AUTHOR_EN = "Le Nguyen Nhu Anh";
  const AUTHOR_VI = "Lê Nguyễn Như Anh";
  const CONTACT = "https://edtechcorner.com/contact";
  const YEAR = "2026";

  type Card = { id: string; title: string; body: string[]; from: string };
  const C = {
    en: {
      tagline: "English–English · English–Vietnamese · Vietnamese–English",
      intro:
        "An offline learner's dictionary for Vietnamese learners and teachers of English. The page layout follows modern advanced learner's dictionaries, but all of the content comes from open data or was newly written for this dictionary and labelled AI.",
      appVer: "App version",
      dataVer: "Data version",
      built: "built",
      nav: ["Credits", "How the content is made", "Data sources", "Licence"],
      creditsTitle: "Credits",
      createdBy: "Created by",
      author: AUTHOR_EN,
      contactTitle: "Contact the author (opens in your web browser)",
      authorRole: "Founder, Edtech Corner · concept, editorial direction and design",
      thanksTitle: "With thanks to",
      thanks: [
        "the contributors to Wiktionary (English and Vietnamese editions);",
        "Tatu Ylonen and the Wiktextract / kaikki.org project;",
        "the Open English WordNet team;",
        "Tono Laboratory, Tokyo University of Foreign Studies (CEFR-J), and Octanove Labs;",
        "the contributors to Tatoeba;",
        "skywind3000 (ECDICT).",
      ],
      toolsTitle: "AI tools",
      tools:
        "The learner layer was drafted by Google Gemini 3.8 Flash. The software was built with the help of Claude (Anthropic).",
      glance: "At a glance",
      glanceItems: [
        ["headwords", "English headwords"],
        ["entries", "entries (word + part of speech)"],
        ["entries_ai", "entries with an AI learner layer"],
        ["vi_headwords", "Vietnamese headwords"],
      ],
      howTitle: "How the content is made",
      howIntro:
        "Each kind of information has its own basis. Content marked AI was generated by a model and checked automatically, not by a human editor.",
      from: "Source",
      cards: [
        {
          id: "words",
          title: "Word list and frequency",
          body: [
            "Headwords, phrasal verbs and idioms come from English Wiktionary.",
            "Words are ranked by frequency using the British National Corpus (BNC) and COCA ranks in ECDICT; the better of the two ranks is used.",
            "The 20,000 most frequent words form the core set that gets the full learner treatment. The Top 3000 and Top 5000 badges come from the same ranking. They are not the Oxford 3000/5000 lists.",
          ],
          from: "Wiktionary · ECDICT (BNC/COCA ranks)",
        },
        {
          id: "defs",
          title: "Definitions",
          body: [
            "Learner layer (core words): new definitions in simple English, plus guidewords, grammar codes and register labels. They were drafted by AI from the Wiktionary senses. The AI was told to keep only the senses learners need, put the most common senses first, and never copy wording from commercial dictionaries. Marked AI.",
            "Full layer: every Wiktionary sense, unchanged. AI content never replaces it; you can switch between the two layers.",
          ],
          from: "Wiktionary · Gemini (AI)",
        },
        {
          id: "cefr",
          title: "CEFR levels",
          body: [
            "Word level (badge next to the headword): taken from the CEFR-J Vocabulary Profile 1.5 (A1–B2) and the Octanove Vocabulary Profile (C1–C2). Matching uses the word and its part of speech. If a word is listed at more than one level, the lowest is kept. Words not in these lists have no word level.",
            "Sense level (badge next to a meaning): an AI estimate for that meaning, marked AI. Treat it as guidance only.",
            "The English Vocabulary Profile and the Oxford 3000/5000 lists are not used.",
          ],
          from: "CEFR-J · Octanove · Gemini (AI)",
        },
        {
          id: "ipa",
          title: "Pronunciation",
          body: [
            "IPA comes from Wiktionary: UK = Received Pronunciation, US = General American. If Wiktionary has none, the transcription from ECDICT is shown.",
            "Audio uses the Windows text-to-speech voices installed on your computer; there are no recordings yet. If no British voice is installed, the UK button uses an American voice.",
          ],
          from: "Wiktionary · ECDICT · Windows voices",
        },
        {
          id: "vi",
          title: "Vietnamese meanings",
          body: [
            "Vietnamese meanings are chosen in this order: (1) an AI translation for each learner sense, marked AI, which uses Vietnamese Wiktionary glosses as hints when they match; (2) English Wiktionary translation tables, attached to the closest sense; (3) blocks of meanings by part of speech from Vietnamese Wiktionary.",
          ],
          from: "Wiktionary (EN, VI) · Gemini (AI)",
        },
        {
          id: "vien",
          title: "Vietnamese–English",
          body: [
            "Vietnamese entries come from English Wiktionary. A reverse index is built from all the Vietnamese meanings above. Searching works with or without diacritics.",
          ],
          from: "Wiktionary · reverse index",
        },
        {
          id: "ex",
          title: "Examples",
          body: [
            "There are three kinds of example: short examples from Wiktionary (not literary quotations); original examples written by AI, with Vietnamese translations, marked AI; and real English–Vietnamese sentence pairs from Tatoeba, translated by people.",
          ],
          from: "Wiktionary · Gemini (AI) · Tatoeba",
        },
        {
          id: "thes",
          title: "Synonyms, opposites and word family",
          body: [
            "Synonym sets and opposites come from Open English WordNet. The word family and related phrases come from the derived terms in Wiktionary.",
          ],
          from: "Open English WordNet · Wiktionary",
        },
        {
          id: "origin",
          title: "Word origin and usage notes",
          body: ["These come from Wiktionary etymologies and usage notes, shortened for display."],
          from: "Wiktionary",
        },
        {
          id: "forms",
          title: "Word forms and spelling help",
          body: [
            "Inflected forms such as went → go come from the Wiktionary form tables.",
            "Spelling suggestions are worked out on your computer by comparing letters (edit distance); no other data is used.",
          ],
          from: "Wiktionary · built-in",
        },
        {
          id: "ai",
          title: "About the AI content",
          body: [
            "Model: Google Gemini 3.8 Flash. The model received the Wiktionary senses and the Vietnamese Wiktionary glosses as its input.",
            "Each answer is checked automatically for structure, and every sense it returns must point back to a real Wiktionary sense. Answers that fail the check are discarded and run again.",
            "Every AI line carries the AI label and is stored separately from the source data. AI content can contain mistakes; compare it with the full Wiktionary layer when in doubt.",
          ],
          from: "Gemini (AI)",
        },
      ] as Card[],
      srcTitle: "Data sources",
      srcIntro: "Only these sources are used. Each is downloaded with a recorded checksum so the data can be rebuilt exactly.",
      th: ["Source", "Licence", "Attribution", "Retrieved"],
      licTitle: "Licence",
      appLicTitle: "The app: free licence",
      appLic: [
        `© ${YEAR} ${AUTHOR_EN}, Edtech Corner. ${APP_NAME} is free of charge.`,
        "You may install and use it free of charge for personal study, for teaching and within your organisation.",
        "You may give copies of the unmodified installer to others, free of charge.",
        "You may not sell the app or charge for it, remove its credits or notices, or distribute modified versions without the author's permission.",
        "The app is provided “as is”, without warranty of any kind. The author is not liable for any loss arising from its use or from errors in the content.",
        "The name and the logo belong to Edtech Corner.",
      ],
      dataLicTitle: "The dictionary data: CC BY-SA 4.0",
      dataLic: [
        "The dictionary database is licensed under Creative Commons Attribution-ShareAlike 4.0 (creativecommons.org/licenses/by-sa/4.0), because most of its source data uses that licence. You may reuse it if you credit the sources and share your work under the same licence.",
        "Other sources keep their own licences (see the table above): Tatoeba sentences CC BY 2.0 FR, Open English WordNet CC BY 4.0, ECDICT MIT, CEFR-J free with citation.",
        "The app licence above does not limit any right you have under these data licences.",
      ],
      swTitle: "Third-party software",
      sw: [
        "Tauri (MIT / Apache-2.0)",
        "Svelte and SvelteKit (MIT)",
        "SQLite (public domain), rusqlite (MIT)",
        "Microsoft Edge WebView2 Runtime (Microsoft licence terms)",
      ],
      privacy: "Privacy: the app works fully offline and never sends your searches, word lists or settings anywhere.",
    },
    vi: {
      tagline: "Anh–Anh · Anh–Việt · Việt–Anh",
      intro:
        "Từ điển offline cho người Việt học và dạy tiếng Anh. Bố cục mục từ theo kiểu từ điển người học nâng cao hiện đại. Toàn bộ nội dung lấy từ dữ liệu mở, hoặc được viết mới cho từ điển này và gắn nhãn AI.",
      appVer: "Phiên bản app",
      dataVer: "Phiên bản dữ liệu",
      built: "dựng ngày",
      nav: ["Ghi công", "Cơ sở nội dung", "Nguồn dữ liệu", "Giấy phép"],
      creditsTitle: "Ghi công",
      createdBy: "Tác giả",
      author: AUTHOR_VI,
      contactTitle: "Liên hệ tác giả (mở bằng trình duyệt web)",
      authorRole: "Nhà sáng lập Edtech Corner · ý tưởng, định hướng biên soạn và thiết kế",
      thanksTitle: "Xin cảm ơn",
      thanks: [
        "những người đóng góp cho Wiktionary (bản tiếng Anh và tiếng Việt);",
        "Tatu Ylonen và dự án Wiktextract / kaikki.org;",
        "nhóm Open English WordNet;",
        "Phòng nghiên cứu Tono, Đại học Ngoại ngữ Tokyo (CEFR-J), và Octanove Labs;",
        "những người đóng góp cho Tatoeba;",
        "skywind3000 (ECDICT).",
      ],
      toolsTitle: "Công cụ AI",
      tools: "Lớp người học do Google Gemini 3.8 Flash soạn nháp. Phần mềm được xây dựng với sự hỗ trợ của Claude (Anthropic).",
      glance: "Số liệu",
      glanceItems: [
        ["headwords", "từ đầu mục tiếng Anh"],
        ["entries", "mục từ (từ + từ loại)"],
        ["entries_ai", "mục từ có lớp người học (AI)"],
        ["vi_headwords", "từ đầu mục tiếng Việt"],
      ],
      howTitle: "Cơ sở nội dung",
      howIntro:
        "Mỗi loại thông tin dựa trên một cơ sở riêng. Nội dung gắn nhãn AI do mô hình sinh ra và chỉ được kiểm tra tự động, chưa qua người biên tập.",
      from: "Nguồn",
      cards: [
        {
          id: "words",
          title: "Danh sách từ và tần suất",
          body: [
            "Từ đầu mục, cụm động từ và thành ngữ lấy từ Wiktionary tiếng Anh.",
            "Từ được xếp hạng tần suất theo thứ hạng BNC (Kho ngữ liệu quốc gia Anh) và COCA có trong ECDICT; lấy thứ hạng cao hơn trong hai.",
            "20.000 từ thông dụng nhất là bộ lõi, được biên soạn đầy đủ cho người học. Nhãn Top 3000 và Top 5000 cũng tính theo thứ hạng này, không phải danh sách Oxford 3000/5000.",
          ],
          from: "Wiktionary · ECDICT (thứ hạng BNC/COCA)",
        },
        {
          id: "defs",
          title: "Định nghĩa",
          body: [
            "Lớp người học (bộ từ lõi) gồm định nghĩa mới bằng tiếng Anh đơn giản, từ gợi ý nghĩa, mã ngữ pháp và nhãn văn phong. AI soạn nháp lớp này từ các nghĩa Wiktionary. AI được yêu cầu chỉ giữ nghĩa cần cho người học, xếp nghĩa phổ biến lên trước và không chép câu chữ của từ điển thương mại. Có nhãn AI.",
            "Lớp đầy đủ là mọi nghĩa Wiktionary, giữ nguyên. Nội dung AI không bao giờ thay thế lớp này, và bạn chuyển qua lại được giữa hai lớp.",
          ],
          from: "Wiktionary · Gemini (AI)",
        },
        {
          id: "cefr",
          title: "Cấp độ CEFR",
          body: [
            "Cấp độ của từ (nhãn cạnh từ đầu mục) lấy từ CEFR-J Vocabulary Profile 1.5 (A1–B2) và Octanove Vocabulary Profile (C1–C2), so khớp theo từ và từ loại. Nếu một từ có nhiều cấp độ thì giữ cấp thấp nhất. Từ không có trong hai bộ này thì không có cấp độ từ.",
            "Cấp độ của nghĩa (nhãn cạnh từng nghĩa) là ước lượng của AI cho riêng nghĩa đó, có nhãn AI. Chỉ nên dùng để tham khảo.",
            "Từ điển không dùng English Vocabulary Profile hay danh sách Oxford 3000/5000.",
          ],
          from: "CEFR-J · Octanove · Gemini (AI)",
        },
        {
          id: "ipa",
          title: "Phát âm",
          body: [
            "Phiên âm IPA lấy từ Wiktionary: UK theo giọng chuẩn Anh (RP), US theo giọng Mỹ phổ thông (GA). Khi Wiktionary không có thì dùng phiên âm của ECDICT.",
            "Âm thanh dùng giọng đọc máy (TTS) cài sẵn trong Windows; chưa có bản ghi âm người thật. Nếu máy chưa cài giọng Anh-Anh, nút UK sẽ đọc bằng giọng Mỹ.",
          ],
          from: "Wiktionary · ECDICT · giọng đọc Windows",
        },
        {
          id: "vi",
          title: "Nghĩa tiếng Việt",
          body: [
            "Nghĩa tiếng Việt được chọn theo thứ tự ưu tiên: (1) bản dịch của AI cho từng nghĩa trong lớp người học, có nhãn AI, dùng nghĩa Wiktionary tiếng Việt làm gợi ý khi khớp; (2) bảng dịch của Wiktionary tiếng Anh, gắn vào nghĩa gần nhất; (3) khối nghĩa theo từ loại của Wiktionary tiếng Việt.",
          ],
          from: "Wiktionary (Anh, Việt) · Gemini (AI)",
        },
        {
          id: "vien",
          title: "Việt–Anh",
          body: [
            "Mục từ tiếng Việt lấy từ Wiktionary tiếng Anh, cộng với chỉ mục đảo ngược dựng từ mọi nghĩa tiếng Việt ở trên. Có thể tra có dấu hoặc không dấu.",
          ],
          from: "Wiktionary · chỉ mục đảo ngược",
        },
        {
          id: "ex",
          title: "Ví dụ",
          body: [
            "Có ba loại ví dụ: câu ví dụ ngắn của Wiktionary (không lấy trích dẫn văn chương); câu ví dụ do AI viết mới, kèm bản dịch tiếng Việt, có nhãn AI; và cặp câu Anh–Việt thật từ Tatoeba, do người dịch.",
          ],
          from: "Wiktionary · Gemini (AI) · Tatoeba",
        },
        {
          id: "thes",
          title: "Đồng nghĩa, trái nghĩa, họ từ",
          body: [
            "Nhóm đồng nghĩa và từ trái nghĩa lấy từ Open English WordNet. Họ từ và cụm từ liên quan lấy từ phần từ phái sinh của Wiktionary.",
          ],
          from: "Open English WordNet · Wiktionary",
        },
        {
          id: "origin",
          title: "Nguồn gốc từ và ghi chú cách dùng",
          body: ["Lấy từ phần từ nguyên và ghi chú cách dùng của Wiktionary, rút gọn khi hiển thị."],
          from: "Wiktionary",
        },
        {
          id: "forms",
          title: "Dạng từ và gợi ý chính tả",
          body: [
            "Dạng biến đổi (ví dụ went → go) lấy từ bảng biến cách của Wiktionary.",
            "Gợi ý chính tả do app tự tính trên máy bằng cách so sánh từng chữ cái (khoảng cách sửa); không dùng thêm dữ liệu nào.",
          ],
          from: "Wiktionary · tính sẵn trong app",
        },
        {
          id: "ai",
          title: "Về nội dung AI",
          body: [
            "Mô hình là Google Gemini 3.8 Flash. Đầu vào là các nghĩa Wiktionary và nghĩa gợi ý từ Wiktionary tiếng Việt.",
            "Mỗi câu trả lời được kiểm tra tự động về cấu trúc, và mỗi nghĩa trả về phải trỏ đúng một nghĩa Wiktionary có thật. Câu trả lời không đạt bị loại và chạy lại.",
            "Mọi dòng AI đều có nhãn AI và lưu riêng, không ghi đè dữ liệu nguồn. Nội dung AI có thể sai; khi nghi ngờ, hãy so với lớp Wiktionary đầy đủ.",
          ],
          from: "Gemini (AI)",
        },
      ] as Card[],
      srcTitle: "Nguồn dữ liệu",
      srcIntro: "Từ điển chỉ dùng các nguồn dưới đây. Mỗi nguồn khi tải về đều được ghi mã kiểm tra, để có thể dựng lại đúng dữ liệu.",
      th: ["Nguồn", "Giấy phép", "Ghi công", "Lấy ngày"],
      licTitle: "Giấy phép",
      appLicTitle: "Ứng dụng: giấy phép miễn phí",
      appLic: [
        `© ${YEAR} ${AUTHOR_VI}, Edtech Corner. ${APP_NAME} được cung cấp miễn phí.`,
        "Bạn được cài đặt và sử dụng miễn phí để tự học, giảng dạy và dùng trong tổ chức của mình.",
        "Bạn được chia sẻ miễn phí bản cài đặt nguyên vẹn cho người khác.",
        "Bạn không được bán hay thu phí cho ứng dụng, gỡ bỏ phần ghi công hoặc thông báo bản quyền, hay phát hành bản đã sửa đổi khi chưa có sự đồng ý của tác giả.",
        "Ứng dụng được cung cấp “nguyên trạng”, không kèm bất kỳ bảo đảm nào. Tác giả không chịu trách nhiệm về thiệt hại phát sinh từ việc sử dụng hay từ sai sót trong nội dung.",
        "Tên và logo thuộc về Edtech Corner.",
      ],
      dataLicTitle: "Dữ liệu từ điển: CC BY-SA 4.0",
      dataLic: [
        "Cơ sở dữ liệu từ điển phát hành theo giấy phép Creative Commons Ghi công – Chia sẻ tương tự 4.0 (creativecommons.org/licenses/by-sa/4.0), vì phần lớn dữ liệu nguồn dùng giấy phép này. Bạn được dùng lại dữ liệu nếu ghi công nguồn và chia sẻ sản phẩm theo cùng giấy phép.",
        "Các nguồn khác giữ giấy phép riêng (xem bảng trên): câu Tatoeba theo CC BY 2.0 FR, Open English WordNet theo CC BY 4.0, ECDICT theo MIT, CEFR-J miễn phí và bắt buộc trích dẫn.",
        "Giấy phép ứng dụng ở trên không hạn chế bất kỳ quyền nào bạn có theo các giấy phép dữ liệu này.",
      ],
      swTitle: "Phần mềm bên thứ ba",
      sw: [
        "Tauri (MIT / Apache-2.0)",
        "Svelte và SvelteKit (MIT)",
        "SQLite (phạm vi công cộng), rusqlite (MIT)",
        "Microsoft Edge WebView2 Runtime (điều khoản của Microsoft)",
      ],
      privacy: "Quyền riêng tư: ứng dụng chạy hoàn toàn offline, không gửi từ đã tra, danh sách từ hay cài đặt của bạn đi đâu cả.",
    },
  };

  // Tên/giấy phép nguồn trong DB viết bằng tiếng Việt; giao diện English dùng bản dịch theo id nguồn.
  const SRC_EN: Record<string, [string, string?]> = {
    kaikki_en: ["English Wiktionary, English entries (Wiktextract, kaikki.org)"],
    kaikki_vi: ["English Wiktionary, Vietnamese entries (Wiktextract, kaikki.org)"],
    viwikt: ["Vietnamese Wiktionary, full dump (Wiktextract, kaikki.org)"],
    oewn: ["Open English WordNet 2025", "CC BY 4.0 (based on the Princeton WordNet licence)"],
    cefrj: ["CEFR-J Vocabulary Profile 1.5", "Free for research and commercial use; citation required"],
    octanove: ["Octanove Vocabulary Profile C1/C2 1.0"],
    tatoeba_eng: ["Tatoeba, English sentences"],
    tatoeba_vie: ["Tatoeba, Vietnamese sentences"],
    tatoeba_links: ["Tatoeba, Vietnamese–English sentence links"],
    ecdict: ["ECDICT (BNC/COCA frequency ranks and fallback IPA only)"],
    gemini: ["Gemini 3.8 Flash (via Antigravity CLI)", "AI-generated content, labelled AI"],
  };

  const c = $derived(C[ui.lang]);
  const fmt = (n: number | undefined) => (n ?? 0).toLocaleString(ui.lang === "vi" ? "vi-VN" : "en-GB");
  let sectionEls: HTMLElement[] = $state([]);
  // Liên kết ngoài: mở bằng trình duyệt mặc định (app không tự kết nối mạng, không điều hướng cửa sổ app).
  function openExternal(e: MouseEvent, url: string) {
    e.preventDefault();
    if (inTauri) openUrl(url).catch(() => {});
    else window.open(url, "_blank", "noopener");
  }
  const jump = (i: number) => sectionEls[i]?.scrollIntoView({ behavior: "smooth", block: "start" });
</script>

<section class="about">
  <header class="hero">
    <img src={logo} alt="" width="72" height="72" />
    <div>
      <h1>{APP_NAME}</h1>
      <div class="tag">{c.tagline}</div>
      <div class="vers">
        <span>{c.appVer} <b>{status.app_version ?? "—"}</b></span>
        <span>{c.dataVer} <b>{status.meta.data_version ?? "—"}</b>{#if status.meta.build_date}{" · "}{c.built} {status.meta.build_date.slice(0, 10)}{/if}</span>
      </div>
    </div>
  </header>
  <p class="intro">{c.intro}</p>

  <nav class="toc">
    {#each c.nav as label, i}<button onclick={() => jump(i)}>{label}</button>{/each}
  </nav>

  <h2 bind:this={sectionEls[0]}>{c.creditsTitle}</h2>
  <div class="credit-grid">
    <div class="card author">
      <div class="k">{c.createdBy}</div>
      <a class="name" href={CONTACT} title={c.contactTitle} onclick={(e) => openExternal(e, CONTACT)}>{c.author}</a>
      <a class="contact" href={CONTACT} title={c.contactTitle} onclick={(e) => openExternal(e, CONTACT)}>{CONTACT.replace("https://", "")}</a>
      <div class="role">{c.authorRole}</div>
      <div class="k sub">{c.toolsTitle}</div>
      <p>{c.tools}</p>
    </div>
    <div class="card">
      <div class="k">{c.thanksTitle}</div>
      <ul>{#each c.thanks as x}<li>{x}</li>{/each}</ul>
    </div>
  </div>
  <div class="glance">
    {#each c.glanceItems as [key, label]}
      <div><b>{fmt(status.counts[key])}</b><span>{label}</span></div>
    {/each}
  </div>

  <h2 bind:this={sectionEls[1]}>{c.howTitle}</h2>
  <p class="muted">{c.howIntro}</p>
  <div class="cards">
    {#each c.cards as card (card.id)}
      <article class="card how" class:wide={card.id === "ai"}>
        <h3>{card.title}{#if card.id === "ai"} <Badge kind="ai" text="AI" />{/if}</h3>
        {#each card.body as p}<p>{p}</p>{/each}
        <div class="from"><span>{c.from}:</span> {card.from}</div>
      </article>
    {/each}
  </div>

  <h2 bind:this={sectionEls[2]}>{c.srcTitle}</h2>
  <p class="muted">{c.srcIntro}</p>
  <div class="tbl">
    <table>
      <thead><tr>{#each c.th as h}<th>{h}</th>{/each}</tr></thead>
      <tbody>
        {#each sources as s (s.id)}
          {@const tr = ui.lang === "en" ? SRC_EN[s.id] : undefined}
          <tr>
            <td>{tr?.[0] ?? s.name}{#if s.url}<div class="url">{s.url.replace(/^https?:\/\//, "").split("/").slice(0, 3).join("/")}</div>{/if}</td>
            <td>{tr?.[1] ?? s.license}</td>
            <td>{s.attribution ?? ""}</td>
            <td class="nowrap">{s.retrieved_at?.slice(0, 10) ?? ""}</td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>

  <h2 bind:this={sectionEls[3]}>{c.licTitle}</h2>
  <div class="card lic">
    <h3>{c.appLicTitle}</h3>
    <ul>{#each c.appLic as x}<li>{x}</li>{/each}</ul>
  </div>
  <div class="card lic">
    <h3>{c.dataLicTitle}</h3>
    {#each c.dataLic as x}<p>{x}</p>{/each}
  </div>
  <div class="card lic">
    <h3>{c.swTitle}</h3>
    <ul>{#each c.sw as x}<li>{x}</li>{/each}</ul>
  </div>
  <p class="muted foot">{c.privacy}</p>
</section>

<style>
  .about {
    max-width: 920px;
  }
  .hero {
    display: flex;
    gap: 18px;
    align-items: center;
    padding: 18px 20px;
    border-radius: 12px;
    background: var(--brand-bg);
    color: var(--brand-ink);
    box-shadow: var(--shadow);
  }
  .hero img {
    border-radius: 16px;
    background: #fff;
    flex: none;
  }
  .hero h1 {
    font-family: var(--serif);
    margin: 0 0 2px;
    font-size: 1.6rem;
    line-height: 1.2;
  }
  .tag {
    opacity: 0.9;
    font-size: 0.92rem;
  }
  .vers {
    margin-top: 8px;
    display: flex;
    flex-wrap: wrap;
    gap: 6px 18px;
    font-size: 0.82rem;
    opacity: 0.92;
  }
  .intro {
    margin: 16px 0 10px;
    line-height: 1.6;
  }
  .toc {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
    margin: 8px 0 6px;
  }
  .toc button {
    border: 1px solid var(--line);
    background: var(--surface);
    color: var(--accent);
    border-radius: 999px;
    padding: 5px 12px;
    font: inherit;
    font-size: 0.85rem;
    cursor: pointer;
  }
  .toc button:hover {
    background: var(--accent-soft);
  }
  h2 {
    font-family: var(--serif);
    font-size: 1.3rem;
    margin: 28px 0 8px;
    padding-bottom: 6px;
    border-bottom: 2px solid var(--accent-soft);
    scroll-margin-top: 12px;
  }
  h3 {
    margin: 0 0 6px;
    font-size: 1rem;
    color: var(--accent);
    display: flex;
    align-items: center;
    gap: 8px;
  }
  .card {
    background: var(--surface);
    border: 1px solid var(--line);
    border-radius: 10px;
    padding: 14px 16px;
    box-shadow: var(--shadow);
  }
  .card p {
    margin: 0 0 8px;
    line-height: 1.55;
  }
  .card ul {
    margin: 0;
    padding-left: 18px;
    line-height: 1.6;
  }
  .credit-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px;
  }
  .k {
    font-size: 0.72rem;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: var(--ink-3);
    font-weight: 600;
    margin-bottom: 4px;
  }
  .k.sub {
    margin-top: 14px;
  }
  .author .name {
    font-family: var(--serif);
    font-size: 1.35rem;
    font-weight: 700;
    color: var(--ink);
  }
  .author a.name {
    display: inline-block;
    text-decoration: none;
  }
  .author a.name:hover {
    color: var(--accent);
    text-decoration: underline;
  }
  .author .contact {
    display: block;
    width: fit-content;
    font-size: 0.8rem;
    color: var(--accent);
    margin-bottom: 4px;
  }
  .author .role {
    color: var(--ink-2);
    font-size: 0.9rem;
  }
  .glance {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 10px;
    margin-top: 12px;
  }
  .glance div {
    background: var(--surface-2);
    border-radius: 10px;
    padding: 10px 12px;
    display: flex;
    flex-direction: column;
  }
  .glance b {
    font-size: 1.25rem;
    color: var(--accent);
  }
  .glance span {
    font-size: 0.8rem;
    color: var(--ink-2);
  }
  .cards {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px;
  }
  .how {
    display: flex;
    flex-direction: column;
  }
  .how.wide {
    grid-column: 1 / -1;
  }
  .how p {
    font-size: 0.92rem;
  }
  .from {
    margin-top: auto;
    padding-top: 6px;
    border-top: 1px dashed var(--line);
    font-size: 0.8rem;
    color: var(--gw);
  }
  .from span {
    color: var(--ink-3);
  }
  .tbl {
    overflow-x: auto;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.88rem;
    background: var(--surface);
    border: 1px solid var(--line);
  }
  th,
  td {
    text-align: left;
    padding: 8px 10px;
    border-bottom: 1px solid var(--line);
    vertical-align: top;
  }
  th {
    background: var(--surface-2);
    font-weight: 600;
  }
  .url {
    font-family: var(--mono);
    font-size: 0.74rem;
    color: var(--ink-3);
    word-break: break-all;
    user-select: text;
  }
  .nowrap {
    white-space: nowrap;
  }
  .lic {
    margin-bottom: 12px;
  }
  .muted {
    color: var(--ink-3);
    font-size: 0.9rem;
  }
  .foot {
    margin: 6px 0 24px;
  }
  @media (max-width: 760px) {
    .credit-grid,
    .cards {
      grid-template-columns: 1fr;
    }
    .glance {
      grid-template-columns: 1fr 1fr;
    }
  }
</style>
